//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise_2.DB
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class ComicParams
    {
        public int Id { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Author { get; set; }
        public string Type { get; set; }
    
        public virtual Comic Comic { get; set; }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine($"ID: {Id}");
            sb.AppendLine($"Language: {Language}");
            sb.AppendLine($"Country: {Country}");
            sb.AppendLine($"Author: {Author}");
            sb.AppendLine($"Type: {Type}");

            return sb.ToString();
        }
    }
}
