//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise_2.DB
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class Comic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Barcode { get; set; }
        public System.DateTime DateOfPublish { get; set; }
        public int CategoryId { get; set; }
        public int PublisherId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ComicParams ComicParams { get; set; }
        public virtual Publisher Publisher { get; set; }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine($"ID: {Id}");
            sb.AppendLine($"Name: {Name}");
            sb.AppendLine($"Description: {Description}");
            sb.AppendLine($"Price: {Price}");
            sb.AppendLine($"Barcode: {Barcode}");
            sb.AppendLine($"Date of publish: {DateOfPublish}");
            sb.AppendLine($"Category id: {CategoryId}");
            sb.AppendLine($"Publisher id: {PublisherId}");
            sb.AppendLine($"ComicParams id: {ComicParams.Id}");

            return sb.ToString();
        }
    }
}
